---
- name: Change hostname 
  hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - Restart system

- name: Change hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"
  register: output
  changed_when: output.stdout != ""

- name: Change /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1       {{ inventory_fqdn | default("") }}       {{ inventory_hostname }}'
    state: present
  notify:
    - Restart system